### PR TITLE
Set geodata server according to new routes

### PR DESCRIPTION
**Pull request by SBRitter**
Since the routes of our geodata service will be updated, the URLs used to query the index have to be changed in this project, too. 

See https://github.com/hbz/geodata/pull/33

### CODE REVIEW

**Comment by acka47** [comment]
The context is listed twice in the JSON-LD, see [line 3758](https://travis-ci.org/hbz/lobid-organisations/builds/147746253#L3758) of the build log:

```json
"@context": [  
      "http://beta.lobid.org/organisations/context.jsonld",
      "http://beta.lobid.org/organisations/context.jsonld"
   ],
```

**Comment by acka47** [comment]
Hmm, the JSON playground doesn't give an error when providing two contexts, see. e.g. http://tinyurl.com/gucvsux

**Comment by SBRitter** [comment]
Build is now passing. However, only with metafacture reverted to an earlier commit, see https://github.com/hbz/metafacture-core/issues/9

**Comment by dr0i** [comment]
+1

**Pull request merged**
