### PR TITLE
128 provenance info

### PR DESCRIPTION
**Pull request by TobiasNx**
The indexing breaks because of the last commit. I am not sure why. I add two elements to `mainEntityOfPage`. It could be that `used` is a weird array. Could you have a look. see #128

### CODE REVIEW

**Comment by fsteeg** [comment]
Didn't look closely yet, but there are a lot of failing tests. Also there are conflicts, so maybe something went wrong when branching off or something, and this is not actually the correct state? I'd suggest resolving the conflicts first and then we can take a closer look at the failures.

**Comment by TobiasNx** [comment]
I merged the master into this. The error still there. I assume that the old version of elasticSearch is not able to work with this mixed array:

```
			"used": [
				{
					"id": "http://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-294&recordSchema=PicaPlus-xml&version=1.1",
					"sourceOrganisation": {
						"id": "https://sigel.staatsbibliothek-berlin.de/vergabe/isil/",
						"label": "Deutsche ISIL-Agentur und Sigelstelle an der Staatsbibliothek zu Berlin"
					}
				},
				"https://github.com/metafacture/metafacture-core",
				"https://github.com/hbz/lobid-organisations/blob/master/conf/fix-sigel.fix",
				"https://github.com/hbz/lobid-organisations/blob/master/conf/fix-enriched.fix"
			]
```

**Comment by TobiasNx** [comment]
ElasticSearch-Docu says: [Arrays with a mixture of data types are not supported: [ 10, "some string" ]](https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html)

That could be the problem, but I dont know why this is possible in ElasticSearch with OERSI: See [@context here](https://oersi.org/resources/aHR0cHM6Ly9vY3cubWl0LmVkdS9jb3Vyc2VzLzUtMDUtcHJpbmNpcGxlcy1vZi1pbm9yZ2FuaWMtY2hlbWlzdHJ5LWlpaS1zcHJpbmctMjAwNS9yZXNvdXJjZXMvZXhhbTNfczA1XzIwMDUv?format=json)

**Comment by TobiasNx** [comment]
@dr0i can you help?

**Comment by acka47** [comment]
> I dont know why this is possible in ElasticSearch with OERSI: See [@context here](https://oersi.org/resources/aHR0cHM6Ly9vY3cubWl0LmVkdS9jb3Vyc2VzLzUtMDUtcHJpbmNpcGxlcy1vZi1pbm9yZ2FuaWMtY2hlbWlzdHJ5LWlpaS1zcHJpbmctMjAwNS9yZXNvdXJjZXMvZXhhbTNfczA1XzIwMDUv?format=json)

I think this is due to the fact that `@context` is not indexed.

**Comment by TobiasNx** [comment]
@acka47 and I decided to kick out the metafacture links to only use the sourceData as object for now.

**Comment by TobiasNx** [comment]
like this:
```

"used": [
		{
			"id": "http://services.dnb.de/sru/bib?operation=searchRetrieve&query=isl%3DDE-294&recordSchema=PicaPlus-xml&version=1.1",
			"sourceOrganisation": {
				"id": "https://sigel.staatsbibliothek-berlin.de/vergabe/isil/",
				"label": "Deutsche ISIL-Agentur und Sigelstelle an der Staatsbibliothek zu Berlin"
				}
	]
```

**Pull request merged**
