### PR TITLE
MANUAL MERGE of issue/#38 and master

### PR DESCRIPTION
**Pull request by philboeselager**

### CODE REVIEW

**Comment by fsteeg** [comment]
I did a full data transformation and indexing on your branch as described in the README (starting at https://github.com/hbz/lobid-organisations#downloads), but I still get the `postOfficeBoxNumber: 10 07 55` for `DE-1393-BOT` (the original issue described in #38). Is there anything special I have to do?

**Comment by philboeselager** [comment]
@fsteeg : I did some bigger changes, namely:
- separate the part of the stream that splits the XML sources (dump and updates) into single XML files
--> the further stream processing is ensured to take place after all sources have been splitted now. This is supposed to solve the update problem mentioned above finally.
- delete some temporary or helper methods or classes that are not needed any more
Can you please test once more?

**Comment by fsteeg** [comment]
CI failed (errors in the Maven build).

**Comment by fsteeg** [comment]
* I can reproduce the fix, but I had to change the passed value documented in https://github.com/hbz/lobid-organisations#index from 25000000 to 15000000. If I understand the fix correctly, the smaller size is expected, so we should update the README
* As we discussed the other day, we should not add a dependency to the lodmill repo, but instead move the `XmlEntitySplitter` and `XmlFilenameWriter` to our metafacture-core fork and open a corresponding pull request against metafacture-core. @dr0i, could you help with that step?
* The pom contains two new plugins: `maven-assembly-plugin` and `maven-dependency-plugin`. The latter sets up MySQL, I assume this is related to the lodmill-rd dependency? After moving the  `XmlEntitySplitter` and `XmlFilenameWriter` to metafacture-core, could we remove these?
* The pom contains two new dependencies to Groovy and Lucene. They are not used in the `lobid-organisations` codebase as far as I see, and I can `mvn clean install` without them. Are these also related to the lodmill-rd dependency and can we remove them after the move?
* I was able to reproduce the fix even without the new `TripleRematch` (and its superclass). Is this expected? Was this class introduced for a different problem? Do we have a corresponding issue? If it indeed is unrelated to #38, we shouldn't merge it as part of this pull request.
* There are small test files in `src/main/resources/input/`. That folder was previously empty, the test files are in `src/test/resources/input/`. Did you commit these accidentally?

**Comment by philboeselager** [comment]
The inclusion of TripleRematch evolved from the long multi-branch status and the try, to tidy up everything. In order to let the commit history be correct, I've created a new branch: issue/#38_v4. I'm going to answer the questions above there.

**Comment by philboeselager** [comment]
Issues have been transferred to new pull requests #78 and #80. Closing.

**Pull request closed without merging**
