### PR TITLE
Set up localized URLs for API documentation

### LINKED ISSUE #292: Implement language specific URLs
We now have the `Content-Language` header implemented (#287) but it seems as if language-specific URLs are best practice, see e.g. http://ux.stackexchange.com/questions/68368/should-language-be-part-of-a-website-url/68375 or https://support.google.com/webmasters/answer/182192.

I think, we should also do this, it will especially help us with the hypothes.is problem. What do you think?

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #292

Deployed to staging:

http://test.lobid.org/organisations/api
http://test.lobid.org/organisations/api/de
http://test.lobid.org/organisations/api/en

### CODE REVIEW

**Comment by acka47** [comment]
+1 can you please add a <link rel="canonical" href="http://lobid.org/organisations/api/" /> to http://lobid.org/organisations/api/de so that I don't have to add the annotations all over again? I am not sure how to add it to the scala.html...

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/organisations/api/de

**Comment by acka47** [comment]
+1 It works!

**Comment by dr0i** [comment]
+1

**Pull request merged**
