### PR TITLE
Add link to API usage policy

### PR DESCRIPTION
**Pull request by Phu2**

### CODE REVIEW

**Comment by kaena83** [comment]
It says "All checks have failed" - should I merge it anyways?

**Comment by Phu2** [comment]
Deployed to http://test.lobid.org/organisations/api/de
@kaena83 Please have a look

**Comment by kaena83** [comment]
This looks fine.

**Review by kaena83 — APPROVED** [review]

**Review by acka47 — APPROVED** [review]
+1

**Comment by Phu2** [comment]
@dr0i Please review and merge

**Review by dr0i — APPROVED** [review]

**Pull request merged**
