### PR TITLE
Update DBS data

### PR DESCRIPTION
**Pull request by acka47**
See #94

### CODE REVIEW

**Comment by acka47** [comment]
Here we go with another try. But the commit history looks much cleaner. :-)

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/organisations

**Comment by acka47** [comment]
Comparing resources on production and staging I noticed the following differences:

- [ ] Email information currently is included on staging although we removed it some time ago (#111) because of privacy converns, see e.g. http://stage.lobid.org/organisations/DBS-AA277.json
- [ ] "classification" information is missing
- [ ] "collection" (size) information is missing

For the last two points see e.g. http://stage.lobid.org/organisations/DBS-AA381.json and http://lobid.org/organisations/DBS-AA381.json.

I will have a look at the last two points.

**Comment by acka47** [comment]
Re. "classification", I obviously wrote the wrong `typ_id`s into the mapping as the column contains a 
 lot of values like "30", "60", "70" which are mainly not in the mapping:
https://github.com/hbz/lobid-organisations/blob/d3ec9ab02b09ec38e532db57beb6f01c825b12de/conf/morph-enriched.xml#L603-L617 

For values that are in the mapping (e.g. "21") the results look good, see for example http://stage.lobid.org/organisations/DBS-AB154.json.

Re. "collection", this is actually largely working as the field is only missing in around 360 entries that have value "0" in `bestandsgroessenklasse_id`, see http://stage.lobid.org/organisations/search?q=_exists_%3AdbsID+AND+NOT+_exists_%3Aisil+AND+NOT+_exists_%3Acollects&location=.

Re. "email", I am quite sure it was added because in the new export the name for the column is the same as the name for email from ISIL registry ("email") so that the email is added because of this part of the morph:

https://github.com/hbz/lobid-organisations/blob/d3ec9ab02b09ec38e532db57beb6f01c825b12de/conf/morph-enriched.xml#L134-L137

I will change the name in the export to something different ("email_dbs").

**Comment by acka47** [comment]
As I don't have access to the dbs database via VPN I will make the corrections in the morph and add an updated export and test file tomorrow.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/organisations

**Comment by acka47** [comment]
There are >400 orgs less in the new index. The DBS export has 390 entries less than the old one. We might investigate why this is so but I think it is ok as we export all libraries that are active DBS participants. The rest can be explained by increased merging of DBS and ISIL records. So , I think this is ok.

**Comment by acka47** [comment]
We found some empty "isil" values, see e.g. http://stage.lobid.org/organisations/DBS-QJ396.json. This must have something to do with the morph changes. Will revert the morph adjustments (replacing "isigel" by "isil") and update the SQL query to name the field accordingly.

**Comment by fsteeg** [comment]
Deployed to stage: http://stage.lobid.org/organisations

**Comment by acka47** [comment]
+1 I think we can finally deploy this on production.

**Pull request merged**
