### PR TITLE
Support customizable aggregations, none as default

### PR DESCRIPTION
**Pull request by fsteeg**
See https://github.com/hbz/lobid-resources-web/issues/26

Deployed to staging:

http://test.lobid.org/organisations/search?q=hbz&format=json (no aggregations)
http://test.lobid.org/organisations/search?q=hbz&format=json&aggregations=type,classification.label.en (supported)
http://test.lobid.org/organisations/search?q=hbz&format=json&aggregations=name (unsupported)

### CODE REVIEW

**Comment by acka47** [comment]
Looks good, also the error message when asking for an unsupported aggregation. I would have expected this to work, though: http://test.lobid.org/organisations/search?q=hbz&format=json&aggregations=type,classification.id 

I guess we can add useful aggregations at a later point on request by API users.

**Comment by ChristophEwertowski** [comment]
+1 By the way: Shouldn't it be "Nordrhein-**W**estfälischer Bibliotheksverbund"? http://test.lobid.org/organisations/DE-605

**Comment by acka47** [comment]
> By the way: Shouldn't it be "Nordrhein-**W**estfälischer Bibliotheksverbund"? 

Yes, you are right. This isn't coming from the Sigelverzeichnis (see http://sigel.staatsbibliothek-berlin.de/aenderungen-mitteilen/?isil=DE-605 where the name is "hbz - Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen") but from the DBS. There are different ways to fix this:

1. Adjust the dbs.zip file
2. Prioritize names from ISL registry over DBS.

I suggest to fix the csv for now. Regarding the [relevant part of the morph](https://github.com/hbz/lobid-organisations/blob/041bb549186c85905dab1489af7833b68e5c5455/conf/morph-enriched.xml#L89-L97): How are names chosen by now when there are different forms in both source data sets? Is DBS always prioritized or is it random?

**Comment by fsteeg** [comment]
> 1. Adjust the dbs.zip file

We should not do that, since that would be overridden when we get a new DBS dump.

**Comment by dr0i** [comment]
+1

**Pull request merged**
