### PR TITLE
Use Hydra vocabulary and structure for search results

### PR DESCRIPTION
**Pull request by fsteeg**
Will partially resolve https://github.com/hbz/lobid-resources-web/issues/26

Deployed to staging, see: http://test.lobid.org/organisations/search?q=hbz&format=json

### CODE REVIEW

**Comment by dr0i** [comment]
I think `aggregation`is missing context.jsonld.

**Comment by fsteeg** [comment]
We won't add a mapping for `aggregation` (briefly discussed this with @acka47).

**Comment by dr0i** [comment]
+1

**Comment by acka47** [comment]
+1

**Pull request merged**
