### PR TITLE
Remove isPrimaryTopicOf & primaryTopic.

### LINKED ISSUE #310: Remove isPrimaryTopicOf link to ZDB catalog
Similar to https://github.com/hbz/lobid-resources/issues/232. We don't need this information and the link can easily be generated from the ISIL.

This means to remove https://github.com/hbz/lobid-organisations/blob/d0271043c5426bbac443a3f21e137d4f5cce9db9/conf/context.jsonld#L82-L85 , https://github.com/hbz/lobid-organisations/blob/041bb549186c85905dab1489af7833b68e5c5455/conf/morph-enriched.xml#L327-L330 and adjust the test files.

The example at http://lobid.org/organisations/api/de has also to be adjusted.

### PR DESCRIPTION
**Pull request by acka47**
Fixes #310.

### CODE REVIEW

**Comment by acka47** [comment]
I did not get lobid-organisations running locally (again) but obviously this field wans't tested at all so that the test fields needn't be adjusted. Please deploy for functional review, @fsteeg .

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.lobid.org/organisations/search?q=*&format=json
http://test.lobid.org/organisations/context.jsonld

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Now might be the right moment to pull in the example at http://lobid.org/organisations/api/de from production.

**Pull request merged**
