### PR TITLE
Add wikidata links, remove DBpedia links

### LINKED ISSUE #320: Add wikidata links
We should add `owl:sameAs` links based on ISIL matches to wikidata. First step: Create a lookup table at https://github.com/hbz/lookup-tables. Here is an example query to get a wikidata ID by ISIL: http://tinyurl.com/ztujked

### LINKED ISSUE #336: Replace mo:wikipedia
Taking a look at the rdfs:domain of mo:wikipedia we should use another property in the context of lobid-organisations. From the Music Ontology:

```
mo:wikipedia
    mo:level "1" ;
    a owl:ObjectProperty ;
    rdfs:comment """
        Used to link an work, an expression of a work, a manifestation of a work, 
        a person, an instrument or a musical genre to its corresponding WikiPedia page. 
        The full URL should be used, not just the WikiName.
    """ ;
    rdfs:domain [
        a owl:Class ;
        owl:unionOf (frbr:Work
            frbr:Expression
            frbr:Manifestation
            frbr:Item
            foaf:Agent
            mo:Instrument
            mo:Genre
        )
    ] ;
    rdfs:isDefinedBy <http://purl.org/ontology/mo/> ;
    rdfs:label "wikipedia" ;
    rdfs:range foaf:Document ;
    rdfs:subPropertyOf foaf:isPrimaryTopicOf ;
    vs:term_status "stable" .
```

### PR DESCRIPTION
**Pull request by acka47**
Fixes #320, fixes #336.

### CODE REVIEW

**Comment by acka47** [comment]
Regarding the removal of the wikipedia link, there is some more code in the repo that probably should also be adjusted, see https://github.com/hbz/lobid-organisations/search?q=wikipedia&type=Code&utf8=%E2%9C%93

**Comment by fsteeg** [comment]
Deployed to staging: http://stage.lobid.org/organisations

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
It is already merged but nonetheless I give a +1

**Pull request merged**
