### PR TITLE
Update old dbs.csv testfile to new formating of dbs.csv

### PR DESCRIPTION
**Pull request by TobiasNx**
The old testfile was not formated as the newest version of the dbs.csv that we fetch from the SQL Database of DBS.

I updated it and also updated two tests.

### CODE REVIEW

**Comment by TobiasNx** [comment]
I put this PR on halt after the next deployment.

**Comment by TobiasNx** [comment]
Why was this branch closed?

**Comment by dr0i** [comment]
Hm, Idk anymore. Should have written down my thoughts.
Most probably because the branch whicht this PR wanted to merge into was already merged into master.
You can , I think, if you want, change the the branch you want to merge into to master.

**Comment by dr0i** [comment]
Repopened.

**Comment by TobiasNx** [comment]
I already merged the commit with adjustments.. sorry was to fast: https://github.com/hbz/lobid-organisations/commit/aba753865ff7c10d23ab60fad10f5335295e022f

**Pull request closed without merging**
