### PR TITLE
Translate morph into fix and switch to fix

### PR DESCRIPTION
**Pull request by TobiasNx**
Related to #452 and replaces #454 

This PR replaces the morph transformation with a fix transformation.

@acka47 and @fsteeg could you have a look at GUI of test.lobid.org/organisations and the json-data there. I finished the transformation i my opinion.

I also included fixes for:
#361 - added gndId and links to lobid-gnd
#411 - added sigils
#458 - added an `note[]`-element
#457 and #76 added `replacedBy`, `replaces` and `dissolutionDate`
#99 added libraries.org links
#269 removed test entries
#309 added `parentOrganisation`
#383 added wikidata 
#428 use https for isil registry links
#128 add `provenance` Info but without links to metafacture [since the early version breaks elasticSearch](https://github.com/hbz/lobid-organisations/pull/463)

### CODE REVIEW

**Comment by TobiasNx** [comment]
Also adding a strictness and logging as in lobid-resources would be nice.

**Comment by TobiasNx** [comment]
Bugs spotted:
- telephone needs to be fixed: https://github.com/hbz/lobid-organisations/pull/450/commits/cf244837fabd804af9e09ea2840ddbbe830af4af

**Comment by TobiasNx** [comment]
- openHoursOther was wrongly mapped: fixed (unfortunately) in https://github.com/hbz/lobid-organisations/pull/450/commits/271c94024ff59d09ae3eacb722c935db9da4ebbe#diff-3396aff3b89ff796e6dedd9a4b3089be5edeb8428fd6762a51218bb678d9350aL303
- property gndId needs to be gndIdentifier: fixed in https://github.com/hbz/lobid-organisations/pull/450/commits/271c94024ff59d09ae3eacb722c935db9da4ebbe
- update context: fixed in: https://github.com/hbz/lobid-organisations/pull/450/commits/a7289395ce573fc32235683fbf5ed5792e9284fc

**Comment by dr0i** [comment]
Offline agreed to more checking functionality vs code review (which is a bit unhandy re amount of commits and changed files).

- [ ]  test nwbib and lobid-resource with these new organisations data GUI-wise
- [ ] do updates via OAI-PMH work?
- [x] are ntriples still served

**Comment by dr0i** [comment]
Updates seems to work. After `bash -x cron.sh` the resource http://test.lobid.org/organisations/DE-4229#! with `"dateCreated":"15-08-23"` exists in test system (and not yet in production).
So I think this PR is fine :+1:

**Pull request merged**
