### PR TITLE
Issue/#38 : Sigel Updating removes old obselete information

### PR DESCRIPTION
**Pull request by philboeselager**
With respect to @fsteeg's comment dated September 1st, 2015 from hbz/lobid-organisations#68 :

> I can reproduce the fix, but I had to change the passed value documented in https://github.com/hbz/lobid-organisations#index from 25000000 to 15000000. If I understand the fix correctly, the smaller size is expected, so we should update the README

This is a result of the TripleRematch function and therefore not part of this branch (any more).

> As we discussed the other day, we should not add a dependency to the lodmill repo, but instead move the XmlEntitySplitter and XmlFilenameWriter to our metafacture-core fork and open a corresponding pull request against metafacture-core. @dr0i, could you help with that step?

I've moved these files to metafacture-core and created pull requests against culturegraph and hbz.

> The pom contains two new plugins: maven-assembly-plugin and maven-dependency-plugin. The latter sets up MySQL, I assume this is related to the lodmill-rd dependency? After moving the XmlEntitySplitter and XmlFilenameWriter to metafacture-core, could we remove these?

Correct. Entries have been removed.

> The pom contains two new dependencies to Groovy and Lucene. They are not used in the lobid-organisations codebase as far as I see, and I can mvn clean install without them. Are these also related to the lodmill-rd dependency and can we remove them after the move?

Correct. They have been removed.

> I was able to reproduce the fix even without the new TripleRematch (and its superclass). Is this expected? Was this class introduced for a different problem? Do we have a corresponding issue? If it indeed is unrelated to #38, we shouldn't merge it as part of this pull request.

Correct, these issues ahd merged. I've splitted the files according to their issues again. I'm going to branch the TripleRematch "story" next.

> There are small test files in src/main/resources/input/. That folder was previously empty, the test files are in src/test/resources/input/. Did you commit these accidentally?

Yes, you're right. Everything is "back" in src/test/resources/input/ .

### CODE REVIEW

**Comment by philboeselager** [comment]
The travis build is going to be "red" as long as the new files (XmlEntitySplitter, XmlFilenameWriter...) are not merged in hbz/metafacture-core.

**Comment by dr0i** [comment]
You mean https://github.com/hbz/metafacture-core/pull/7 ? We really should refactor that by renaming the class. It's totally misleading (my fault).

**Comment by fsteeg** [comment]
Restarted build after merge of https://github.com/hbz/metafacture-core/pull/7

**Comment by philboeselager** [comment]
Is not working yet because of the renaming in metafacture (XmlEntitySplitter --> XmlElementSplitter). I'm going to amend that.

**Pull request merged**
