### PR TITLE
Issue/#50

### PR DESCRIPTION
**Pull request by philboeselager**
The solution to issue #49 and #50 was:
- Setup a geodata microsoervice (not included here)
- Make use of it in the metafacture pipe via RestMap

The fix comprised in the other commit is not directly connected to this issue. It makes that there is 1 single TripleRematch object in the entire pipe and it would have occured anyway. Not sure, why it occured. Looks very similar to the one we had using TripleSort. Eventually we had a pull from culturegraph/metafacture which changed some of the memory behaviour? Anyway, the problem is solved now.

### CODE REVIEW

**Comment by dr0i** [comment]
Also, no test is provided. Without that test, I it's not clear if this works.

**Comment by philboeselager** [comment]
A test would base / rely on the assumption that the remote geo service works. Should we implement it anyway?

**Comment by dr0i** [comment]
I would have in a mind a integration test with in-build elasticsearch and tests with test data. See e.g. https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/test/java/org/lobid/lodmill/MabXml2ElasticsearchLobidTest.java#L53 which shows how to use the local elasticsearch nodebuilder, it's easy to setup.

**Comment by philboeselager** [comment]
While having tried to implement a test (see https://github.com/hbz/lobid-organisations/tree/issue/%2350_withTest ), it pointed out, that the configuration of the "GET"-Syntax is differing too much between the Microservice of the productive code and the surrogate Elasticsearch instance used within the test. Nevertheless, the approach to implement an integration test that queries a running production server is still valuable. As agreed, we won't implement that for now. Merging.

**Comment by philboeselager** [comment]
A new issue was created for the later implementation of an integration test, see #88 .

**Pull request merged**
