### PR TITLE
Remove @'s from data (@type->type, @id->id)

### PR DESCRIPTION
**Pull request by philboeselager**
Renamed "@type" to "type" and "@id" to "id" in any occurrence. Is this it?

### CODE REVIEW

**Comment by fsteeg** [comment]
Since the context already defines the `"id": "@id","type": "@type"` mappings this should work. You can test the validity of the resulting JSON-LD in the playground as described in https://github.com/hbz/lobid-organisations#query.

**Comment by acka47** [comment]
See #51 & #52 .

**Comment by fsteeg** [comment]
After merging of https://github.com/hbz/lobid-organisations/pull/78 this conflicts. I tried merging master and resolving the conflict, but then the tests fail. Somehow the diff does not show the actual differences, something is weird. @philboeselager perhaps we could have a look at this together tomorrow at 10?

**Comment by philboeselager** [comment]
Yes, I'm guess it's something about the merge. Let's see tomorrow.

**Pull request merged**
