### PR TITLE
Fix problems with reconciliation endpoint

### LINKED ISSUE #385: Problems with reconciliation endpoint
Talking with @literarymachine today about an import for CRG, we noticed that the reconciliation endpoint has two problems:

1. Running reconciliation on the name column of the customer list from EDB, obviously identical strings aren't matched, e.g. "Universitätsbibliothek der RWTH Aachen":

reconciliation-problem

2. As you can see, no matches are automatically added but have to be confirmed. Usually matches are added automatically in open refine, see e.g. this result of reconciliating with the OEr WOrld Map endpoint.This may have something to do with the match score lobid returns.

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #385.

### CODE REVIEW

**Comment by dr0i** [comment]
10 tests failed.

**Comment by dr0i** [comment]
Hm, tests still failing.Is this good?

**Comment by fsteeg** [comment]
Now fixed: https://travis-ci.org/hbz/lobid-organisations/builds/277183788

**Comment by dr0i** [comment]
ok

**Pull request merged**
