### PR TITLE
Change structure of stocksize and subject data

### LINKED ISSUE #281: Describe collection as separate object
A [discussion on twitter](https://twitter.com/fsteeg/status/805347749797498880) mad eme think about the way we say something about the collection of an organization. Generally, I think we should tweak the modelling a bit. Instead of:

```json
"id": "http://lobid.org/organisations/DE-38M#!",
"stocksize" : {
    "id" : "http://purl.org/lobid/stocksize#n09",
    "type" : "Concept",
    "label" : {
      "de" : "300.001 - 1.000.000",
      "en" : "300,001 - 1,000,000"
    }
  },
  "subject" : [ "Medizin" ]
``` 

We should do something like this:

```json
  "id": "http://lobid.org/organisations/DE-38M#!",
  "collects": [ {
    "type": "Collection",
    "extent" : {
      "id" : "http://purl.org/lobid/stocksize#n09",
      "type" : "Concept",
      "label" : {
        "de" : "300.001 - 1.000.000",
        "en" : "300,001 - 1,000,000"
      }
    },
    "subject" : [ "Medizin" ]
  } ]
``` 

This is a better way to express it and would enable us to add more info about a collection – or several collections maintained by an organization – in the future. Sorry that I come up with this now, but I think it shouldn't be too much work to implement it before official launch.

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #281 

Deployment in progress, self-assigning for now.

### CODE REVIEW

**Comment by fsteeg** [comment]
Deployed to staging, see http://test.lobid.org/organisations/DE-38M?format=json

**Comment by acka47** [comment]
The updated context is not deployed yet, is it?

**Comment by fsteeg** [comment]
Context is deployed to staging: http://test.lobid.org/organisations/context.jsonld

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
+1

**Pull request merged**
