### PR TITLE
Update map lookup for new quoted ISILs in isil2wikidata.csv

### PR DESCRIPTION
**Pull request by fsteeg**
Changed in https://github.com/hbz/lookup-tables/commit/4c17237

Will resolve https://github.com/hbz/lobid-organisations/issues/426

### CODE REVIEW

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
I don't think we need a review for this, do we? It's ok to directly deploy from my side.

**Comment by fsteeg** [comment]
I will deploy, but leaving a mention of @dr0i here for him to check if the change in the CSV file is OK.

**Comment by dr0i** [comment]
+1

**Pull request merged**
