### PR TITLE
Add api description

### LINKED ISSUE #421: Add information on APIs
Originated in a request by @donboern, followed up by [this twitter thread](https://twitter.com/acka47/status/1143820540785897472) and Jakob publishing a [manual](https://verbundwiki.gbv.de/display/VZG/Schnittstellen) on how to add the data to the system.

By now there are several entries with information on PAIA, DAIA, SRU or OpenURL:

- Test org: http://ld.zdb-services.de/resource/organisations/ZDB-Test2
- TU Hamburg: http://ld.zdb-services.de/resource/organisations/DE-830
- ZBW: http://ld.zdb-services.de/resource/organisations/DE-206H

We will have to add this to the lobid-organisations JSON-LD. The documentation for the relevant field 009Q is at https://sigel.staatsbibliothek-berlin.de/vergabe/adressenformat/856/.

 I will propose a solution for the test org example in a separate comment.

### PR DESCRIPTION
**Pull request by dr0i**
- expand morph rules
- add test

Resolves #421.

### CODE REVIEW

**Comment by dr0i** [comment]
Deployed to staging.
All: https://stage.lobid.org/organisations/search?q=_exists_%3AavailableChannel.
Getting DAIA implementers: https://stage.lobid.org/organisations/search?q=availableChannel.serviceType%3A"DAIA"

**Comment by acka47** [comment]
Against our usual workflow, I am doing the functional review in the PR.

I took a look at this and we need one round of adjustments:

1. We should only add `availableChannel` when the value in subfield `x` is one of: `DAIA`, `PAIA`, `SRU`, `Z39.50` or `OpenURL` (see also Jakob's [manual](https://verbundwiki.gbv.de/display/VZG/Schnittstellen)), currently resulting in only [eight entries](https://stage.lobid.org/organisations/search?q=availableChannel.serviceType%3A%22OpenURL%22+OR+availableChannel.serviceType%3A%22DAIA%22+OR+availableChannel.serviceType%3A%22PAIA%22+OR+availableChannel.serviceType%3A%22SRU%22&location=) being expanded 
2. We should a) always have an array with `availableChannel` and b) add all channels if one institution provides more than one of those four.

Re. 2.), see e.g. `DE-Hil2`:

```xml
<ppxml:tag id="009Q" occ="">
  <ppxml:subf id="u">http://sru.gbv.de/opac-de-hil2</ppxml:subf>
  <ppxml:subf id="x">SRU</ppxml:subf>
  <ppxml:subf id="z">W</ppxml:subf>
</ppxml:tag>
<ppxml:tag id="009Q" occ="">
  <ppxml:subf id="u">https://paia.gbv.de/DE-Hil2/</ppxml:subf>
  <ppxml:subf id="x">PAIA</ppxml:subf>
  <ppxml:subf id="z">W</ppxml:subf>
</ppxml:tag>
<ppxml:tag id="009Q" occ="">
  <ppxml:subf id="u">https://paia.gbv.de/DE-Hil2/daia</ppxml:subf>
  <ppxml:subf id="x">DAIA</ppxml:subf>
  <ppxml:subf id="z">W</ppxml:subf>
</ppxml:tag>
```

In the JSON-LD it should look like this:

```json
{
   "availableChannel":[
      {
         "serviceType":"PAIA",
         "type":"WebAPI",
         "serviceUrl":"https://paia.gbv.de/DE-Hil2/"
      },
      {
         "serviceType":"DAIA",
         "type":"WebAPI",
         "serviceUrl":"https://paia.gbv.de/DE-Hil2/daia"
      },
      {
         "serviceType":"SRU",
         "type":"WebAPI",
         "serviceUrl":"http://sru.gbv.de/opac-de-hil2"
      }
   ]
}
```

**Comment by dr0i** [comment]
Made changes, deployed, @acka47 please test again.

**Comment by acka47** [comment]
Looks great but there is one last thing to do. We need to remove all `ServiceChannel`s with `serviceType` "Weitere Informationen". These are [nearly 7000 museums](https://stage.lobid.org/organisations/search?q=availableChannel.serviceType%3A%22Weitere+Informationen%22) that only link to another registry. It is not a service by those instituions at all.

**Comment by dr0i** [comment]
Changed and deployed. Note that there are nonetheless 4 museums with the "Weitere Informationen" link. To fix these too I have to further investigate the underlying pica. @acka47 if you have time, could you manage to get the pica source of these resources?

**Comment by dr0i** [comment]
Ah @acka47 don't bother, these used the singular form of it. I will adjust the regular expression accordingly.

**Comment by acka47** [comment]
+1 Looks good now, so please deploy to production.

(Note: A lot of links in there still are not really service URLs or at least service in a totaly different sense, e.g. [Benutzungsordnung](https://stage.lobid.org/organisations/search?q=availableChannel.serviceType%3ANutzung), [Standort](https://stage.lobid.org/organisations/search?q=availableChannel.serviceType%3AStandort), [Öffnungszeiten](https://stage.lobid.org/organisations/search?q=availableChannel.serviceType%3A%C3%96ffnungszeiten)). However, I do not think that keeping those is a problem, so we will not remove them now.)

**Comment by dr0i** [comment]
Deployed to production, closed.

**Pull request merged**
